version: "3"

services: 
  db:
    image: postgres:latest
    container_name: database
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      PG_DATA: /var/lib/postgresql/data
    env_file:
      - .env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080